/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6715edd8665bf32377aa078f9bf9d43f)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	API_KEY_COOKIE_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_KEY_COOKIE_SECRET">> {}
}
